In [142]:
import pandas as pd

df = pd.read_csv (r'./dataset.csv')
df

,id,created,facebook_id,gender,age,salary,other_income,parent_num,child_num,marriage,infirm,risk_question,risk_type,categories_version,categories_data,ans_type
0,21,2021-01-28 10:01:05.376329+00:00,2874096129581803,2,21,20000,60000,2,0,1,1,"[4, 3, 3, [4, 3, 1], 2, 3, 3, 3, 3, 3]",3,1,"{'Art': 0, 'Band': 0, 'Chef': 1, 'Mood': 0, 'S...",2
1,22,2021-01-28 10:01:05.912085+00:00,2874096129581803,2,21,20000,60000,2,0,1,1,"[4, 3, 3, [4, 3, 1], 2, 3, 3, 3, 3, 3]",3,2,"{'Art': 0, 'Band': 0, 'Chef': 1, 'Mood': 0, 'S...",2
2,23,2021-01-28 10:51:18.011598+00:00,1467108093486495,1,21,13000,6000,2,0,1,1,"[4, 2, 3, [1, 2, 3, 4], 2, 2, 3, 2, 3, 2]",2,1,"{'Art': 1, 'Band': 1, 'Chef': 0, 'Mood': 0, 'S...",2
3,24,2021-01-28 10:51:19.027727+00:00,1467108093486495,1,21,13000,6000,2,0,1,1,"[4, 2, 3, [1, 2, 3, 4], 2, 2, 3, 2, 3, 2]",2,2,"{'Art': 3, 'Band': 1, 'Chef': 0, 'Mood': 0, 'S...",2
4,25,2021-01-28 11:16:44.181398+00:00,1163951720692153,2,22,25000,360000,4,0,1,1,"[4, 4, 4, [4], 4, 4, 4, 4, 4, 4]",4,1,"{'Art': 2, 'Band': 0, 'Chef': 0, 'Mood': 0, 'S...",2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,88,2021-02-09 14:59:18.179129+00:00,6680332541992110,1,36,12000,0,0,2,2,1,"[3, 3, 1, [1], 2, 2, 3, 2, 4, 3]",2,2,"{'Art': 3, 'Band': 1, 'Chef': 1, 'Mood': 0, 'S...",3
62,89,2021-02-12 03:14:17.466448+00:00,1819910071491921,1,47,80000,0,2,2,2,1,"[2, 2, 3, [1, 2, 3, 4], 3, 2, 3, 3, 3, 4]",2,1,"{'Art': 0, 'Band': 0, 'Chef': 0, 'Mood': 0, 'S...",2
63,90,2021-02-12 03:14:18.021806+00:00,1819910071491921,1,47,80000,0,2,2,2,1,"[2, 2, 3, [1, 2, 3, 4], 3, 2, 3, 3, 3, 4]",2,2,"{'Art': 0, 'Band': 0, 'Chef': 0, 'Mood': 0, 'S...",2
64,91,2021-02-16 08:25:19.036053+00:00,3869634116392861,2,24,80000,2500000,0,2,2,1,"[4, 2, 3, [1], 2, 3, 3, 3, 3, 3]",2,1,"{'Art': 1, 'Band': 0, 'Chef': 0, 'Mood': 0, 'S...",2
65,92,2021-02-16 08:25:20.063376+00:00,3869634116392861,2,24,80000,2500000,0,2,2,1,"[4, 2, 3, [1], 2, 3, 3, 3, 3, 3]",2,2,"{'Art': 1, 'Band': 0, 'Chef': 0, 'Mood': 0, 'S...",2

In [143]:
import json
temp_list = []
for i in df['risk_question']:
    x = json.loads(i)
    temp_list.append(x)
temp_list 
df['risk_question'] = temp_list 

for i in range(1,11):
    df[f'risk_question_{i}'] = df['risk_question'].apply(lambda x:x[i-1])

for i in range(1,5):
    temp_list = []
    for j in df['risk_question_4']:
        if i in j:
            temp_list.append(1)
        else:
            temp_list.append(0)
    df[f'risk_question_4_{i}'] = temp_list
df

,id,created,facebook_id,gender,age,salary,other_income,parent_num,child_num,marriage,...,risk_question_5,risk_question_6,risk_question_7,risk_question_8,risk_question_9,risk_question_10,risk_question_4_1,risk_question_4_2,risk_question_4_3,risk_question_4_4
0,21,2021-01-28 10:01:05.376329+00:00,2874096129581803,2,21,20000,60000,2,0,1,...,2,3,3,3,3,3,1,0,1,1
1,22,2021-01-28 10:01:05.912085+00:00,2874096129581803,2,21,20000,60000,2,0,1,...,2,3,3,3,3,3,1,0,1,1
2,23,2021-01-28 10:51:18.011598+00:00,1467108093486495,1,21,13000,6000,2,0,1,...,2,2,3,2,3,2,1,1,1,1
3,24,2021-01-28 10:51:19.027727+00:00,1467108093486495,1,21,13000,6000,2,0,1,...,2,2,3,2,3,2,1,1,1,1
4,25,2021-01-28 11:16:44.181398+00:00,1163951720692153,2,22,25000,360000,4,0,1,...,4,4,4,4,4,4,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,88,2021-02-09 14:59:18.179129+00:00,6680332541992110,1,36,12000,0,0,2,2,...,2,2,3,2,4,3,1,0,0,0
62,89,2021-02-12 03:14:17.466448+00:00,1819910071491921,1,47,80000,0,2,2,2,...,3,2,3,3,3,4,1,1,1,1
63,90,2021-02-12 03:14:18.021806+00:00,1819910071491921,1,47,80000,0,2,2,2,...,3,2,3,3,3,4,1,1,1,1
64,91,2021-02-16 08:25:19.036053+00:00,3869634116392861,2,24,80000,2500000,0,2,2,...,2,3,3,3,3,3,1,0,0,0
65,92,2021-02-16 08:25:20.063376+00:00,3869634116392861,2,24,80000,2500000,0,2,2,...,2,3,3,3,3,3,1,0,0,0

In [144]:
temp_list = []
for i in df['categories_data']:
    x = json.loads(i.replace("'", '"')) 
    temp_list.append(x)
df['categories_data'] = temp_list

key_list = []
for key in df['categories_data'][0].keys():
    key_list.append(key)
    
for key in key_list:
    df[key] = df['categories_data'].apply(lambda x:x.get(key))
df

,id,created,facebook_id,gender,age,salary,other_income,parent_num,child_num,marriage,...,Media Restoration Service,Religious Place of Worship,"Automotive, Aircraft & Boat",Landmark & Historical Place,Public & Government Service,Automated Teller Machine (ATM),"Beauty, Cosmetic & Personal Care","Science, Technology & Engineering",Non-Governmental Organization (NGO),Environmental Conservation Organization
0,21,2021-01-28 10:01:05.376329+00:00,2874096129581803,2,21,20000,60000,2,0,1,...,0,0,16,0,0,0,1,2,0,0
1,22,2021-01-28 10:01:05.912085+00:00,2874096129581803,2,21,20000,60000,2,0,1,...,0,0,16,0,1,0,2,6,0,0
2,23,2021-01-28 10:51:18.011598+00:00,1467108093486495,1,21,13000,6000,2,0,1,...,0,0,1,0,1,0,3,10,0,0
3,24,2021-01-28 10:51:19.027727+00:00,1467108093486495,1,21,13000,6000,2,0,1,...,0,0,2,0,2,0,3,15,0,0
4,25,2021-01-28 11:16:44.181398+00:00,1163951720692153,2,22,25000,360000,4,0,1,...,0,0,0,0,0,0,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,88,2021-02-09 14:59:18.179129+00:00,6680332541992110,1,36,12000,0,0,2,2,...,0,6,2,2,3,0,20,7,1,0
62,89,2021-02-12 03:14:17.466448+00:00,1819910071491921,1,47,80000,0,2,2,2,...,0,0,2,1,2,0,0,9,3,1
63,90,2021-02-12 03:14:18.021806+00:00,1819910071491921,1,47,80000,0,2,2,2,...,0,0,2,1,5,0,0,13,3,1
64,91,2021-02-16 08:25:19.036053+00:00,3869634116392861,2,24,80000,2500000,0,2,2,...,0,0,9,0,0,0,2,14,0,0
65,92,2021-02-16 08:25:20.063376+00:00,3869634116392861,2,24,80000,2500000,0,2,2,...,0,0,11,0,1,0,3,17,0,0

In [145]:
df.drop(['id', 'created', 'facebook_id', 'risk_question', 'risk_question_4','categories_data'], axis=1, inplace=True)
df.to_csv('pre_process_format.csv')
df

,gender,age,salary,other_income,parent_num,child_num,marriage,infirm,risk_type,categories_version,...,Media Restoration Service,Religious Place of Worship,"Automotive, Aircraft & Boat",Landmark & Historical Place,Public & Government Service,Automated Teller Machine (ATM),"Beauty, Cosmetic & Personal Care","Science, Technology & Engineering",Non-Governmental Organization (NGO),Environmental Conservation Organization
0,2,21,20000,60000,2,0,1,1,3,1,...,0,0,16,0,0,0,1,2,0,0
1,2,21,20000,60000,2,0,1,1,3,2,...,0,0,16,0,1,0,2,6,0,0
2,1,21,13000,6000,2,0,1,1,2,1,...,0,0,1,0,1,0,3,10,0,0
3,1,21,13000,6000,2,0,1,1,2,2,...,0,0,2,0,2,0,3,15,0,0
4,2,22,25000,360000,4,0,1,1,4,1,...,0,0,0,0,0,0,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,1,36,12000,0,0,2,2,1,2,2,...,0,6,2,2,3,0,20,7,1,0
62,1,47,80000,0,2,2,2,1,2,1,...,0,0,2,1,2,0,0,9,3,1
63,1,47,80000,0,2,2,2,1,2,2,...,0,0,2,1,5,0,0,13,3,1
64,2,24,80000,2500000,0,2,2,1,2,1,...,0,0,9,0,0,0,2,14,0,0
65,2,24,80000,2500000,0,2,2,1,2,2,...,0,0,11,0,1,0,3,17,0,0

In [146]:
count = 0
accept_percent = 0.60
for key in key_list:
    i = df[key].isin([0]).sum()
    if i >= len(df.index) * accept_percent:
        print(f'{key} : {i}')
        df.drop(key, axis=1, inplace=True)
        count +=1
print(count)

Band : 46
Chef : 57
Mood : 66
Show : 60
Cause : 62
Color : 66
Gamer : 42
Legal : 54
Topic : 66
Author : 40
Course : 66
Dancer : 50
Editor : 66
Athlete : 49
Cuisine : 66
Profile : 64
Science : 66
Designer : 61
Diseases : 66
Election : 66
Fan Page : 49
Language : 66
Locality : 46
Musician : 45
Producer : 51
Orchestra : 66
Residence : 41
Scientist : 57
Surgeries : 66
Journalist : 50
Agriculture : 44
Labor Union : 66
Nationality : 66
Real Estate : 41
Social Club : 63
Sports Club : 59
Visual Arts : 62
Work Status : 66
Armed Forces : 66
Concert Tour : 57
Entrepreneur : 44
Meeting Room : 66
Talent Agent : 62
Ticket Sales : 65
Work Project : 66
Fashion Model : 53
Film Director : 65
Fitness Model : 65
Literary Arts : 66
Public Toilet : 65
Satire/Parody : 66
Sports Season : 66
Work Position : 66
Campus Building : 41
Digital Creator : 50
Harmonized Page : 66
Performance Art : 66
Performing Arts : 48
Sports Promoter : 64
Theatrical Play : 66
Exchange Program : 66
News Personality : 49
Spiritual Leader : 66
Community Service : 52
Editorial/Opinion : 63
University (NCES) : 66
University Status : 66
Outdoor Recreation : 48
Youth Organization : 62
City Infrastructure : 58
Charity Organization : 55
Motivational Speaker : 55
Private Members Club : 64
Sorority & Fraternity : 64
Religious Organization : 56
Theatrical Productions : 65
Commercial & Industrial : 45
Country Club / Clubhouse : 64
Media Restoration Service : 66
Religious Place of Worship : 53
Landmark & Historical Place : 53
Automated Teller Machine (ATM) : 66
Non-Governmental Organization (NGO) : 55
Environmental Conservation Organization : 62
84

In [147]:
df

,gender,age,salary,other_income,parent_num,child_num,marriage,infirm,risk_type,categories_version,...,Media/News Company,Sports & Recreation,Arts & Entertainment,Advertising/Marketing,Nonprofit Organization,Travel & Transportation,"Automotive, Aircraft & Boat",Public & Government Service,"Beauty, Cosmetic & Personal Care","Science, Technology & Engineering"
0,2,21,20000,60000,2,0,1,1,3,1,...,0,0,1,0,0,0,16,0,1,2
1,2,21,20000,60000,2,0,1,1,3,2,...,2,1,1,0,0,0,16,1,2,6
2,1,21,13000,6000,2,0,1,1,2,1,...,11,1,2,5,3,4,1,1,3,10
3,1,21,13000,6000,2,0,1,1,2,2,...,14,2,6,6,3,6,2,2,3,15
4,2,22,25000,360000,4,0,1,1,4,1,...,5,1,1,1,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,1,36,12000,0,0,2,2,1,2,2,...,64,9,19,8,9,27,2,3,20,7
62,1,47,80000,0,2,2,2,1,2,1,...,15,0,3,1,5,3,2,2,0,9
63,1,47,80000,0,2,2,2,1,2,2,...,20,1,4,2,8,4,2,5,0,13
64,2,24,80000,2500000,0,2,2,1,2,1,...,12,12,1,3,4,10,9,0,2,14
65,2,24,80000,2500000,0,2,2,1,2,2,...,17,20,3,4,4,16,11,1,3,17

In [148]:
df.corr()

,gender,age,salary,other_income,parent_num,child_num,marriage,infirm,risk_type,categories_version,...,Media/News Company,Sports & Recreation,Arts & Entertainment,Advertising/Marketing,Nonprofit Organization,Travel & Transportation,"Automotive, Aircraft & Boat",Public & Government Service,"Beauty, Cosmetic & Personal Care","Science, Technology & Engineering"
gender,1.000000e+00,-5.593634e-01,-7.784781e-02,0.215037,2.042001e-01,-4.010556e-01,-4.587633e-01,NaN,2.780521e-01,-6.731716e-18,...,-0.068829,0.304813,0.084157,0.123949,0.064651,-0.133201,0.245307,0.118687,-0.313498,0.410882
age,-5.593634e-01,1.000000e+00,3.751289e-01,-0.142127,-4.416715e-01,7.444927e-01,8.283283e-01,NaN,-3.295020e-01,2.311629e-17,...,-0.219305,-0.274052,-0.366749,-0.298750,-0.249347,0.020912,-0.181812,-0.250835,-0.017235,-0.499600
salary,-7.784781e-02,3.751289e-01,1.000000e+00,0.262253,-2.071433e-01,2.842689e-01,3.113257e-01,NaN,1.299480e-01,8.370605e-18,...,-0.191344,-0.180405,-0.230911,-0.199299,-0.015795,0.010834,0.094422,-0.176746,-0.044385,-0.009727
other_income,2.150369e-01,-1.421267e-01,2.622526e-01,1.000000,-1.596277e-01,1.656925e-01,1.431530e-01,NaN,2.285523e-02,0.000000e+00,...,0.012553,0.105563,-0.096079,0.185467,0.086995,0.379834,0.117198,-0.100231,-0.016642,0.313292
parent_num,2.042001e-01,-4.416715e-01,-2.071433e-01,-0.159628,1.000000e+00,-4.403978e-01,-4.773926e-01,NaN,4.935014e-01,2.336849e-17,...,0.015568,0.151583,0.103930,0.101764,-0.050434,-0.328444,0.118964,0.098314,-0.100044,0.294017
child_num,-4.010556e-01,7.444927e-01,2.842689e-01,0.165692,-4.403978e-01,1.000000e+00,9.376145e-01,NaN,-3.002782e-01,-3.496874e-18,...,0.005798,-0.176881,-0.202802,-0.096580,-0.093959,0.299658,-0.114026,-0.237807,0.097071,-0.268346
marriage,-4.587633e-01,8.283283e-01,3.113257e-01,0.143153,-4.773926e-01,9.376145e-01,1.000000e+00,NaN,-2.619440e-01,1.721328e-17,...,-0.040908,-0.197216,-0.249205,-0.128186,-0.144140,0.300487,-0.113533,-0.277475,0.090191,-0.316989
infirm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
risk_type,2.780521e-01,-3.295020e-01,1.299480e-01,0.022855,4.935014e-01,-3.002782e-01,-2.619440e-01,NaN,1.000000e+00,1.283967e-17,...,-0.009256,-0.080036,-0.006536,0.131569,-0.179997,-0.093012,0.247889,-0.198580,-0.119891,0.233461
categories_version,-6.731716e-18,2.311629e-17,8.370605e-18,0.000000,2.336849e-17,-3.496874e-18,1.721328e-17,NaN,1.283967e-17,1.000000e+00,...,0.157234,0.062650,0.203116,0.174138,0.077872,0.091675,0.030392,0.182838,0.152193,0.188609
ans_type,-1.741576e-01,1.732975e-01,1.743075e-01,-0.062250,-2.159183e-01,1.809367e-01,2.671970e-01,NaN,1.155401e-01,-1.434385e-17,...,0.121167,-0.223383,0.048617,0.043493,-0.051616,0.180421,-0.028242,-0.123568,0.139642,-0.058043
risk_question_1,5.461857e-01,-9.828107e-01,-3.473421e-01,0.154936,4.058300e-01,-7.611135e-01,-8.274852e-01,NaN,3.376180e-01,0.000000e+00,...,0.223660,0.263542,0.366763,0.298873,0.275320,0.004489,0.174506,0.286347,0.021575,0.484924
risk_question_2,2.887010e-01,-2.348464e-01,1.750762e-01,-0.011548,3.524210e-01,-3.460831e-01,-3.634316e-01,NaN,5.745923e-01,-3.696638e-18,...,0.116582,-0.160623,0.016119,0.141424,0.050461,0.039795,0.107385,0.157568,-0.010839,0.197371
risk_question_3,1.163315e-02,8.647728e-02,3.127651e-01,0.155284,1.442262e-01,2.417194e-02,4.759432e-02,NaN,5.132267e-01,2.928834e-17,...,-0.356361,-0.194598,-0.300715,-0.122745,-0.274675,-0.234516,0.090895,-0.424044,-0.234408,-0.111143
risk_question_5,-4.332836e-02,-2.684081e-02,1.548112e-01,-0.068942,3.787113e-01,-1.209776e-01,-5.539621e-02,NaN,3.808714e-01,2.396590e-17,...,-0.005367,0.126202,-0.160566,-0.182598,-0.254156,-0.194104,-0.103160,-0.048035,-0.094783,-0.046691
risk_question_6,3.572479e-01,-5.219955e-01,4.581629e-02,0.214179,4.232262e-01,-4.295761e-01,-3.992323e-01,NaN,7.461309e-01,-8.075684e-18,...,-0.062765,-0.086388,0.065377,0.183391,0.026797,-0.001111,0.225101,0.002347,-0.049356,0.208729
risk_question_7,1.281125e-02,-1.879702e-01,1.939020e-01,0.056619,3.824678e-01,1.197894e-02,-5.241424e-03,NaN,6.119476e-01,-2.463063e-17,...,0.098369,-0.116898,-0.007010,0.141094,-0.057461,0.066862,0.093451,-0.109532,0.060204,0.119325
risk_question_8,4.073091e-01,-2.563120e-01,1.950543e-01,0.159203,2.668401e-01,-9.688220e-02,-9.428374e-02,NaN,8.234540e-01,-1.177569e-17,...,-0.138841,-0.126064,-0.068820,0.077896,-0.156509,-0.104559,0.134378,-0.282528,-0.236458,0.197382
risk_question_9,6.565322e-02,-7.060352e-02,1.333246e-01,-0.034227,2.346119e-01,1.143500e-01,1.165271e-01,NaN,6.840826e-01,-4.751057e-18,...,0.129825,-0.120467,0.033097,0.041954,-0.154711,0.126405,0.033249,-0.294563,-0.003366,0.048567
risk_question_10,-3.820700e-02,2.025158e-01,2.014692e-01,-0.010881,1.863162e-01,2.844752e-01,2.735513e-01,NaN,3.126178e-01,7.530206e-18,...,-0.105522,-0.093361,-0.138654,-0.042937,-0.281205,-0.092712,0.151704,-0.359187,-0.167826,0.038201
risk_question_4_1,9.736551e-02,5.619110e-02,-1.309695e-01,0.051257,-7.878075e-02,1.437472e-01,1.677256e-01,NaN,-6.119476e-02,2.345774e-18,...,0.064499,0.146704,0.054360,0.046072,-0.015694,0.066862,0.140819,-0.124530,-0.087180,0.217016
risk_question_4_2,-1.487081e-01,3.866176e-01,3.249353e-01,-0.203423,6.268455e-02,2.433321e-01,3.118074e-01,NaN,5.919380e-02,8.509018e-18,...,-0.148607,-0.249486,-0.220018,-0.013927,-0.096595,-0.137193,-0.212982,0.052755,-0.108609,0.054187
risk_question_4_3,-1.586362e-01,-1.890552e-02,2.521002e-01,-0.052302,2.317576e-01,-2.071275e-01,-1.666410e-01,NaN,2.133300e-01,1.275700e-17,...,-0.028473,-0.134886,-0.041172,0.033728,0.060147,-0.045137,0.009228,0.056277,0.118677,0.184808
risk_question_4_4,1.507353e-01,-2.232289e-01,3.445603e-01,-0.152728,4.448646e-01,-3.380326e-01,-3.346716e-01,NaN,6.804959e-01,3.365858e-18,...,-0.114870,-0.118808,-0.105505,0.017904,-0.187052,-0.248697,0.170187,-0.096515,-0.144317,0.179056
Art,1.306054e-01,-3.254992e-01,-3.172261e-01,-0.024918,2.572872e-01,-2.192767e-01,-2.531479e-01,NaN,-1.723357e-02,2.499115e-01,...,0.560850,0.475131,0.602041,0.515470,0.404122,0.266402,0.328683,0.422503,0.391617,0.343287
Actor,2.240178e-01,-4.042244e-01,-2.333001e-01,0.165487,1.210454e-01,-2.131656e-01,-2.492356e-01,NaN,-6.765265e-02,1.080686e-01,...,0.604929,0.667315,0.659291,0.493073,0.424661,0.316389,0.263889,0.543810,0.392565,0.504399
Brand,6.747578e-02,-2.453465e-01,-1.485860e-01,0.103620,-1.377428e-02,-6.258922e-03,-4.215233e-02,NaN,6.087165e-02,7.926257e-02,...,0.878156,0.617434,0.817345,0.697508,0.630902,0.665824,0.564454,0.510701,0.665344,0.485780
Event,4.256027e-02,-3.611916e-01,-2.485300e-02,0.066727,2.581748e-01,-2.155575e-01,-2.534147e-01,NaN,3.630271e-02,1.629462e-01,...,0.629559,0.598350,0.639874,0.382921,0.433002,0.380262,0.252924,0.398630,0.670746,0.386156
Music,1.349532e-01,-3.222673e-01,-3.797348e-01,-0.095513,1.314095e-01,-2.282081e-01,-2.601218e-01,NaN,-2.171603e-01,8.456328e-02,...,0.592416,0.733590,0.642158,0.421256,0.420010,0.244894,0.118059,0.620820,0.413154,0.396310
Artist,1.203392e-01,-4.484107e-01,-2.892889e-01,-0.094835,1.511490e-01,-3.414356e-01,-3.823258e-01,NaN,-4.012982e-02,6.322890e-02,...,0.565647,0.451540,0.725403,0.320422,0.596492,0.198513,0.234894,0.421926,0.318034,0.345632
Sports,2.373686e-01,-2.878023e-01,-2.354819e-01,-0.038445,1.285251e-01,-2.057165e-01,-2.279202e-01,NaN,-8.034474e-02,1.731027e-01,...,0.456164,0.833643,0.554985,0.256776,0.312510,0.118951,0.299231,0.430923,0.268010,0.381882
Writer,-3.569716e-02,-4.522377e-01,-2.934088e-02,0.362796,7.930828e-02,-1.655549e-01,-2.070940e-01,NaN,2.671363e-02,7.535777e-02,...,0.685354,0.342344,0.704060,0.490600,0.686137,0.650672,0.143900,0.447287,0.601681,0.408754
Blogger,-1.761034e-03,-2.549599e-01,-1.774362e-01,0.186291,-9.190432e-02,2.712086e-02,-1.536330e-02,NaN,4.515172e-02,9.738185e-02,...,0.815062,0.318504,0.809398,0.657941,0.703736,0.831904,0.202003,0.396582,0.767448,0.348541
Finance,-8.934700e-03,-2.458261e-01,-1.786105e-02,0.470222,1.426733e-01,-1.063773e-01,-1.169736e-01,NaN,1.756905e-01,9.430710e-02,...,0.247922,-0.009448,0.101683,0.595223,0.246303,0.468504,0.026976,0.300230,0.110138,0.468119
Comedian,2.916232e-01,-3.802793e-01,-2.769665e-01,0.046145,1.620475e-01,-2.991602e-01,-3.352935e-01,NaN,-1.711996e-01,5.190187e-02,...,0.503512,0.730348,0.588014,0.297470,0.516200,0.172408,0.218176,0.633387,0.317134,0.370915
Community,1.111075e-01,-4.176712e-01,-7.328754e-02,0.174747,1.227760e-01,-1.850599e-01,-2.402286e-01,NaN,-7.968873e-02,7.346426e-02,...,0.756873,0.625326,0.782007,0.435021,0.758650,0.447419,0.315053,0.605915,0.521083,0.513333
Education,1.492287e-01,-5.201145e-01,-1.083415e-01,0.188385,2.366338e-01,-2.708093e-01,-3.262622e-01,NaN,7.794869e-02,1.356140e-01,...,0.723883,0.463460,0.793905,0.588106,0.716139,0.471883,0.158863,0.611998,0.446773,0.720027
TV & Movies,6.374708e-02,-2.585619e-01,-2.580242e-01,0.144235,-3.070987e-02,-4.162930e-02,-7.265318e-02,NaN,-1.486235e-01,6.462805e-02,...,0.812944,0.783324,0.745779,0.438251,0.527030,0.554936,0.302179,0.497202,0.613107,0.327790
Just For Fun,1.457476e-01,-4.025696e-01,-3.317107e-01,-0.063324,6.995619e-02,-2.256110e-01,-2.795869e-01,NaN,-9.902220e-02,1.930708e-01,...,0.677142,0.535366,0.833400,0.373630,0.650662,0.328429,0.133959,0.478220,0.524831,0.358270
Local Service,-2.222510e-02,-2.657116e-01,-2.096603e-02,0.113799,1.672657e-01,-5.054080e-02,-8.234325e-02,NaN,1.349798e-01,2.406931e-01,...,0.760905,0.392546,0.702515,0.799648,0.610180,0.591230,0.461974,0.532172,0.524870,0.688718
Musician/Band,1.943529e-01,-3.109696e-01,-2.264274e-01,-0.093736,1.996819e-01,-3.099634e-01,-3.309465e-01,NaN,-2.308277e-01,7.330848e-02,...,0.388935,0.752246,0.563736,0.257784,0.390902,0.004609,0.138908,0.600061,0.334818,0.322644
Video Creator,2.377168e-01,-3.670720e-01,-4.066570e-01,0.038578,2.666497e-02,-1.969879e-01,-2.431407e-01,NaN,-5.069143e-02,1.796200e-01,...,0.691557,0.720929,0.739757,0.520514,0.497930,0.347529,0.306142,0.476375,0.393443,0.484161
Not a Business,3.008102e-01,-4.409001e-01,-8.198499e-02,0.060972,1.719512e-01,-3.524788e-01,-3.710874e-01,NaN,2.422192e-01,1.325482e-01,...,0.239419,0.280949,0.459864,0.077847,0.367389,0.059728,0.417363,0.128506,0.215338,0.188059
Food & Beverage,-1.485290e-01,-1.014076e-01,-6.815046e-02,0.125700,-1.213804e-01,1.079929e-01,8.541619e-02,NaN,-4.540070e-02,5.244987e-02,...,0.821625,0.415803,0.768057,0.608679,0.651280,0.790845,0.347536,0.406847,0.850876,0.285448
Hotel & Lodging,-2.409241e-01,6.757328e-02,-5.336679e-02,0.148542,-2.234013e-01,2.760191e-01,2.718968e-01,NaN,-7.711223e-02,1.521412e-02,...,0.695484,0.110446,0.561203,0.519273,0.607112,0.906678,0.062658,0.312262,0.656611,0.196507
Medical & Health,-2.830849e-01,-5.622619e-02,1.350437e-01,0.019595,5.411020e-03,1.183973e-01,8.990121e-02,NaN,-5.187758e-02,8.664356e-02,...,0.601600,-0.014989,0.634161,0.430383,0.730966,0.625669,-0.081679,0.481273,0.752394,0.207037
Books & Magazines,1.899192e-01,-3.329632e-01,-2.148470e-01,-0.007330,1.611612e-01,-1.706449e-01,-2.145340e-01,NaN,-1.578612e-02,1.489806e-01,...,0.750112,0.773197,0.710060,0.481254,0.536344,0.304013,0.624638,0.614858,0.376637,0.437660
Shopping & Retail,4.560571e-02,-1.802530e-01,-1.038256e-01,0.137714,-2.841817e-02,5.284001e-02,1.926694e-02,NaN,1.395716e-01,1.324436e-01,...,0.800156,0.471844,0.702292,0.732272,0.476261,0.656650,0.611937,0.358523,0.616558,0.443384
Media/News Company,-6.882891e-02,-2.193045e-01,-1.913439e-01,0.012553,1.556753e-02,5.797952e-03,-4.090773e-02,NaN,-9.255943e-03,1.572344e-01,...,1.000000,0.492924,0.771572,0.656288,0.605525,0.693575,0.321734,0.602892,0.670688,0.437769
Sports & Recreation,3.048129e-01,-2.740519e-01,-1.804049e-01,0.105563,1.515834e-01,-1.768809e-01,-1.972162e-01,NaN,-8.003625e-02,6.264975e-02,...,0.492924,1.000000,0.495747,0.358743,0.273400,0.117450,0.552611,0.466160,0.210707,0.462657
Arts & Entertainment,8.415730e-02,-3.667493e-01,-2.309108e-01,-0.096079,1.039299e-01,-2.028022e-01,-2.492048e-01,NaN,-6.536412e-03,2.031158e-01,...,0.771572,0.495747,1.000000,0.556387,0.772198,0.509769,0.222038,0.580507,0.680740,0.416022
Advertising/Marketing,1.239492e-01,-2.987498e-01,-1.992995e-01,0.185467,1.017641e-01,-9.658046e-02,-1.281860e-01,NaN,1.315691e-01,1.741375e-01,...,0.656288,0.358743,0.556387,1.000000,0.424366,0.573087,0.424866,0.555268,0.394465,0.694005
Nonprofit Organization,6.465094e-02,-2.493472e-01,-1.579503e-02,0.086995,-5.043358e-02,-9.395900e-02,-1.441399e-01,NaN,-1.799972e-01,7.787224e-02,...,0.605525,0.273400,0.772198,0.424366,1.000000,0.565482,0.068227,0.663774,0.520762,0.376546
Travel & Transportation,-1.332010e-01,2.091160e-02,1.083385e-02,0.379834,-3.284440e-01,2.996578e-01,3.004866e-01,NaN,-9.301236e-02,9.167513e-02,...,0.693575,0.117450,0.509769,0.573087,0.565482,1.000000,0.088351,0.303938,0.661816,0.246041
"Automotive, Aircraft & Boat",2.453073e-01,-1.818119e-01,9.442237e-02,0.117198,1.189636e-01,-1.140263e-01,-1.135334e-01,NaN,2.478891e-01,3.039200e-02,...,0.321734,0.552611,0.222038,0.424866,0.068227,0.088351,1.000000,0.205487,0.075972,0.393884
Public & Government Service,1.186874e-01,-2.508346e-01,-1.767458e-01,-0.100231,9.831358e-02,-2.378068e-01,-2.774752e-01,NaN,-1.985802e-01,1.828380e-01,...,0.602892,0.466160,0.580507,0.555268,0.663774,0.303938,0.205487,1.000000,0.300273,0.540861
"Beauty, Cosmetic & Personal Care",-3.134976e-01,-1.723466e-02,-4.438532e-02,-0.016642,-1.000436e-01,9.707099e-02,9.019116e-02,NaN,-1.198911e-01,1.521930e-01,...,0.670688,0.210707,0.680740,0.394465,0.520762,0.661816,0.075972,0.300273,1.000000,0.020936
"Science, Technology & Engineering",4.108821e-01,-4.995996e-01,-9.727097e-03,0.313292,2.940174e-01,-2.683461e-01,-3.169891e-01,NaN,2.334614e-01,1.886087e-01,...,0.437769,0.462657,0.416022,0.694005,0.376546,0.246041,0.393884,0.540861,0.020936,1.000000